name: SuperVanish
main: RamaCoder\Vanish\Vanish
version: 1.0.0
description: Vanish yourself
author: RamaCoder
api: 3.0.0 ALPHA10
commands:
  vanish:
    description: "Vanish your self"
    aliases: [v]
permissions:
  supervanish.spectate:
    description: "Vanish use perm"
    default: op
