---
name: SuperVanish
main: RamaCoder\Vanish\Vanish
version: 1.0.0
description: This plugin make you to vanish or invisibility with typing in chat /vanish or /v
author: RamaCoder
api: 3.0.0 ALPHA10
commands:
  vanish:
    description: "Vanish your self"
    aliases: [v]
permissions:
  supervanish.spectate:
    description: "Vanish perm"
    default: op
...
